// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuDyBrFQ4F4qlLL3lzN8s6_pegW_rCwxE',
    appId: '1:723690444111:web:a00377aceedb146599613a',
    messagingSenderId: '723690444111',
    projectId: 'tourvia-8fa8c',
    authDomain: 'tourvia-8fa8c.firebaseapp.com',
    storageBucket: 'tourvia-8fa8c.firebasestorage.app',
    measurementId: 'G-YQEWQM644B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-UTmr6k_HW028sQGSWZCi1dSIoLrw9A',
    appId: '1:723690444111:android:f7842cfd625fac1999613a',
    messagingSenderId: '723690444111',
    projectId: 'tourvia-8fa8c',
    storageBucket: 'tourvia-8fa8c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghWP-56N5EV0ol1Yjy2dGbnX6uBp6LUE',
    appId: '1:723690444111:ios:edcbeb8acbeb940e99613a',
    messagingSenderId: '723690444111',
    projectId: 'tourvia-8fa8c',
    storageBucket: 'tourvia-8fa8c.firebasestorage.app',
    iosBundleId: 'com.example.tourvia',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuDyBrFQ4F4qlLL3lzN8s6_pegW_rCwxE',
    appId: '1:723690444111:web:f0a666d93074365399613a',
    messagingSenderId: '723690444111',
    projectId: 'tourvia-8fa8c',
    authDomain: 'tourvia-8fa8c.firebaseapp.com',
    storageBucket: 'tourvia-8fa8c.firebasestorage.app',
    measurementId: 'G-LBM908Z6N2',
  );
}
